- hosts: all
  become: yes

  tasks:

  - name: Stop docker service
    service:
      name: docker
      state: stopped

  - name: Create new Docker data directory
    file:
      path: /data/docker
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: Move Docker data folder to new location
    command: mv /var/lib/docker /data/docker
    args:
      removes: /var/lib/docker

  - name: Create /etc/docker directory
    file:
      path: /etc/docker
      state: directory

  - name: Stat daemon.json
    stat:
      path: /etc/docker/daemon.json
    register: daemon_json

  - name: Create docker config file
    copy:
      dest: /etc/docker/daemon.json
      content: '{}'
    when: not daemon_json.stat.exists

  - name: Update dockerd config to use new data dir
    lineinfile:
      path: /etc/docker/daemon.json  
      regexp: '^.*"data-root".*$'
      line: '"data-root": "/data/docker"'
      backrefs: yes

  - name: Start Docker service
    service:
      name: docker
      state: started
