- hosts: all
  become: yes
  tasks:
    - name: Install LetsEncrypt
      apt:
        name: certbot
        state: present
        update_cache: yes        
    
    - name: Print DOMAIN variable
      debug:
        var: DOMAIN        
    
    - name: Allow incoming traffic on port 80
      ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Generate certificate
      command: certbot certonly --standalone -d {{ DOMAIN }} --agree-tos --register-unsafely-without-email --non-interactive
      
    - name: Block incoming traffic on port 80
      ufw:
        rule: deny
        port: 80
        proto: tcp
