- hosts: all
  become: yes

  tasks:
    - name: Install NFS client packages
      package:
        name: 
          - nfs-common
        state: present

    - name: Create NFS mount directories
      file:
        path: "/nfs/{{ item }}"
        state: directory
      loop:
        - small
        - big

    - name: Mount NFS shares  
      mount:
        src: "192.168.150.5:/mnt/{{ item.src }}"
        path: "/nfs/{{ item.dst }}"
        fstype: nfs
        opts: nfsvers=4
        state: mounted
      loop:
        - { src: 'small', dst: 'small' }
        - { src: 'big', dst: 'big' }

    - name: Add NFS mounts to fstab
      mount:
        src: "192.168.150.5:/mnt/{{ item.src }}" 
        path: "/nfs/{{ item.dst }}"
        fstype: nfs
        state: present
        opts: defaults,nfsvers=4
        dump: 0
        passno: 0
      loop:
       - { src: 'small', dst: 'small' }
       - { src: 'big', dst: 'big' }
