- name: Update packages
  hosts: all
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes
      become: yes
